# Generated by Django 5.2 on 2025-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SOxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Расчет SOx', max_length=100)),
                ('B', models.FloatField()),
                ('S_r', models.FloatField()),
                ('n1_SO2', models.FloatField()),
                ('n2_SO2', models.FloatField()),
                ('itog', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
