# Generated by Django 5.2 on 2025-04-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SOxCalculation',
            new_name='SOx',
        ),
    ]
