# Generated by Django 5.2 on 2025-04-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_soxcalculation_sox'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SOx',
            new_name='SOx_save',
        ),
    ]
