# Generated by Django 5.2 on 2025-04-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_sox_sox_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sox_save',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
