# Generated by Django 5.2 on 2025-04-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_sox_save_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sox_save',
            name='conf_name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
