# Generated by Django 5.2 on 2025-04-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_sox_save_conf_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sox_save',
            name='name',
        ),
    ]
