# Generated by Django 5.2 on 2025-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_sox_save_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sox_save',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
