# Generated by Django 5.2 on 2025-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sox_save_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sox_save',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
