# Generated by Django 5.2 on 2025-04-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_sox_save_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sox_save',
            name='name',
        ),
    ]
