# Generated by Django 5.2 on 2025-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_sox_save_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sox_save',
            name='C',
            field=models.CharField(default='Unnamed Calculation'),
        ),
    ]
