# Generated by Django 5.2 on 2025-04-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_sox_save_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sox_save',
            old_name='C',
            new_name='name',
        ),
    ]
