# Generated by Django 5.2 on 2025-04-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_c_sox_save_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sox_save',
            options={'ordering': ['-created_at'], 'verbose_name': 'Расчет SOx', 'verbose_name_plural': 'Расчеты SOx'},
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='B',
            field=models.FloatField(verbose_name='Параметр B'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='S_r',
            field=models.FloatField(verbose_name='Параметр S_r'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='itog',
            field=models.FloatField(verbose_name='Итоговый результат'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='n1_SO2',
            field=models.FloatField(verbose_name='Коэффициент n1 SO2'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='n2_SO2',
            field=models.FloatField(verbose_name='Коэффициент n2 SO2'),
        ),
        migrations.AlterField(
            model_name='sox_save',
            name='name',
            field=models.CharField(default='Unnamed Calculation', max_length=100, verbose_name='Название расчета'),
        ),
    ]
