# Generated by Django 5.2 on 2025-04-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_sox_save_options_alter_sox_save_b_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOx_fuel_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('T_ad', models.FloatField()),
                ('psi_ZAG', models.FloatField()),
                ('a_T', models.FloatField()),
                ('b_T', models.FloatField()),
                ('h_ZAG', models.FloatField()),
                ('Bp', models.FloatField()),
                ('Vr_Rg', models.FloatField()),
                ('xi', models.FloatField()),
                ('q_ZAG', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('Kg', models.FloatField()),
                ('alpha_ZAG', models.FloatField()),
                ('Nr', models.FloatField()),
                ('Vr', models.FloatField()),
                ('Vsg0', models.FloatField()),
                ('Vv0', models.FloatField()),
                ('R', models.FloatField()),
                ('Vg', models.FloatField()),
                ('Kp', models.FloatField()),
                ('itog', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NOx_save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Wr', models.FloatField()),
                ('Ar', models.FloatField()),
                ('Vr', models.FloatField()),
                ('Nd', models.FloatField()),
                ('alpha_g', models.FloatField()),
                ('alpha_1', models.FloatField()),
                ('R', models.FloatField()),
                ('T_zag', models.FloatField()),
                ('w2_w1', models.FloatField()),
                ('delta_alpha_T', models.FloatField()),
                ('Vr0', models.FloatField()),
                ('Vv0', models.FloatField()),
                ('V_H2O0', models.FloatField()),
                ('Qi_r', models.FloatField()),
                ('Vg', models.FloatField()),
                ('Bp', models.FloatField()),
                ('Kp', models.FloatField()),
                ('burner_type', models.CharField(max_length=50)),
                ('extra_fuel', models.CharField(max_length=50)),
                ('delta', models.FloatField()),
                ('itog', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
