# Generated by Django 5.2 on 2025-04-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_nox_fuel_save_nox_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nox_save',
            old_name='itog',
            new_name='concentration',
        ),
        migrations.AddField(
            model_name='nox_save',
            name='emission_power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nox_save',
            name='specific_emissions',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
