# Generated by Django 5.2 on 2025-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_itog_nox_save_concentration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nox_fuel_save',
            old_name='itog',
            new_name='concentration',
        ),
        migrations.AddField(
            model_name='nox_fuel_save',
            name='emission_power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nox_fuel_save',
            name='standard_concentration',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
